### ISSUE TITLE
Upgrade kotlin and KSP to 1.6.21

### ISSUE THREAD

**Issue by artroman** [mistletoe5215/glide-ksp#1]
Thank you for the library!

Current stable version of kotlin is 1.6.21, and stable version of KSP is 1.6.21-1.0.5.
But I can't use `id 'com.google.devtools.ksp' version "1.6.21-1.0.5" apply false` with `ext.kotlin_version = '1.6.21'` in root build.gradle because it gives build error:
```
[ksp] java.lang.IllegalArgumentException: current module's kotlin version must be at least 1.6.10
	at com.mistletoe.glide.ksp.core.KSPGlideProcessor.process(KSPGlideProcessor.kt:28)
```
It seems that `environment.kotlinVersion.isAtLeast(1, 6, 10)` check is working wrong, because 
`"1.6.21".isAtLeast(1, 6, 10)` should return true.

Also I can't downgrade KSP to 1.6.10-1.0.2 with kotlin 1.6.21 , because it gives error 
`ksp-1.6.10-1.0.2 is too old for kotlin-1.6.21. Please upgrade ksp or downgrade kotlin-gradle-plugin to 1.6.10.`

**Comment by mistletoe5215** [comment]
> i've migrate the deploy repository to maven Central repository ,see it in the latest commit [https://github.com/mistletoe5215/glide-ksp/commit/8d7b737350ecc1f5600ec93ce44e92c3fc3628a3],use the `io.github.mistletoe5215:glide-ksp:1.0.0` instead,the kotlin upgrade to 1.6.20 , ksp to 1.6.10-1.0.2 @ArtRoman

**Comment by mistletoe5215** [comment]
My demo app now works fine,u can have a try @ArtRoman

**Comment by artroman** [comment]
> My demo app now works fine,u can have a try @ArtRoman

Yes, it works great now with kotlin 1.6.21 and ksp-1.6.21, thank you!
