### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by artroman** [mistletoe5215/glide-ksp#2]
```
 //add ksp generated class path into sourceSets
   android {
       //...
       sourceSets {
           main {
               java.srcDirs += ['build/generated/ksp']
           }
       }
```
Is redundant, because ksp folder is already included as sources. It contains generated classes for debug and for release build, so I got errors on full build: 
```
e: build/generated/ksp/debug/kotlin/com/bumptech/glide/GeneratedAppGlideModuleImpl.kt: (15, 16): Redeclaration: GeneratedAppGlideModuleImpl
e: build/generated/ksp/debug/kotlin/com/bumptech/glide/GeneratedRequestManagerFactory.kt: (12, 7): Redeclaration: GeneratedRequestManagerFactory
```
and so on…
\
&nbsp;
```
ksp {
    arg("GlideModule", "com.bumptech.glide.integration.webp.WebpGlideLibraryModule")
}
```
Also, I've spent a lot of time to figure out to place this in the root section of the build.gradle (not .kts), not on `dependencies` block (got example in [room](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-work-release/room/integration-tests/kotlintestapp/build.gradle) repository)

**Comment by artroman** [comment]
According to https://kotlinlang.org/docs/ksp-quickstart.html#use-your-own-processor-in-a-project you dont't need to modify root build.gradle, it's enough to add versioned plugin to module `app/build.gradle` and apply ksp processing:

```
plugins {
    …
    //id 'org.jetbrains.kotlin.kapt'
    id 'com.google.devtools.ksp' version '1.6.10-1.0.2'
}

dependencies {
    …
    implementation "com.github.bumptech.glide:glide:$glide_version"
    //kapt "com.github.bumptech.glide:compiler:$glide_version"
    ksp "com.github.mistletoe5215:glide-ksp:0.0.2"
}

ksp {
    arg("GlideModule", "com.bumptech.glide.integration.webp.WebpGlideLibraryModule")
}
```

**Comment by mistletoe5215** [comment]
in fact,although the   generated sources are included by the ksp plugin,it still needs to declare the sourceSets dirs, in order to let the ide recognize them , then u can  get the code with ide indexing;since the generate task wasn't variant awareness, u may need to clean  project to clear the previous buildType variant artifacts before u begin to run ksp compile task @ArtRoman

**Comment by artroman** [comment]
```
       sourceSets {
           main {
               java.srcDirs += ['build/generated/ksp']
           }
       }
```
Building without this is OK, but IDE is missing generated classes. I'm using glide via wrapper, so I've got all errors in one file. 

But I don't know how to handle this the most correct way.

- 

```
android.applicationVariants.all {
        kotlin {
            sourceSets {
                getByName(name) {
                    kotlin.srcDir("build/generated/ksp/$name/kotlin")
                }
            }
        }
    }
```
is mentioned in [ksp issues](https://github.com/google/ksp/issues/37#issuecomment-1133598640) and is not working because it's for kts (not groovy), and my module is android library (not android application).

- 

```
androidComponents.onVariants { variant ->
        kotlin.sourceSets {
            def name = variant.name
            getByName(name) {
                kotlin.srcDir("build/generated/ksp/$name/kotlin")
            }
        }
    }
```
can't get usable because onVariants has [several declarations](https://developer.android.com/reference/tools/gradle-api/4.2/com/android/build/api/extension/AndroidComponentsExtension#onVariants(com.android.build.api.extension.VariantSelector,%20org.gradle.api.Action)), one via VariantT, another via Action.

- 

```
buildTypes.all { variant ->
        sourceSets {
            main.kotlin.srcDirs += "build/generated/ksp/${variant.name}/kotlin"
        }
    }
```
This looks more correct, but all sources are connected to main, and re-declaration error still occurs.

- 

```
sourceSets {
        main.kotlin.srcDirs += 'build/generated/ksp/debug/kotlin'
    }
```
Even with attaching debug sources for every build type, debug build is ok, but release build without project clean will produce redeclaration error. I think it should be handled by AGP plugin or by IDE itself.

**Comment by mistletoe5215** [comment]
yeah，so i just wrote the parent directory path 'build/generated/ksp',sigh... @ArtRoman

**Comment by artroman** [comment]
> yeah，so i just wrote the parent directory path 'build/generated/ksp',sigh... @ArtRoman

Yes, and it's also breaks build making debug after release, or release after debug without clean.
And I think it's best solution for now, until AGP or IDE will handle this itself.

**Comment by artroman** [comment]
What about my [second](https://github.com/mistletoe5215/glide-ksp/issues/2#issuecomment-1136546622) comment? I believe you shouldn't apply plugin to full project according to manual if you have glide only in one module.

This is enought for me (in app/build.gradle):
```
plugins {
    id 'com.google.devtools.ksp' version '1.6.21-1.0.5'
}

sourceSets {
    main.kotlin.srcDirs += 'build/generated/ksp/'
}

dependencies {
    ksp "io.github.mistletoe5215:glide-ksp:1.0.0"
}

ksp {
    arg("GlideModule", "com.bumptech.glide.integration.webp.WebpGlideLibraryModule")
}
```

**Comment by mistletoe5215** [comment]
> What about my [second](https://github.com/mistletoe5215/glide-ksp/issues/2#issuecomment-1136546622) comment? I believe you shouldn't apply plugin to full project according to manual if you have glide only in one module.
> 
> This is enought for me (in app/build.gradle):
> 
> ```
> plugins {
>     id 'com.google.devtools.ksp' version '1.6.21-1.0.5'
> }
> 
> sourceSets {
>     main.kotlin.srcDirs += 'build/generated/ksp/'
> }
> 
> dependencies {
>     ksp "io.github.mistletoe5215:glide-ksp:1.0.0"
> }
> 
> ksp {
>     arg("GlideModule", "com.bumptech.glide.integration.webp.WebpGlideLibraryModule")
> }
> ```

> cuz my project has multi modules,as u know, my router spi  framework also used `ksp`;if i followed yours ,which means  i 'll need to  declare the plugin  with version '1.6.21-1.0.5'  in my each module.Obviously,it will be more convenient if i declare `plugins {
    id 'com.google.devtools.ksp' version '1.6.21-1.0.5' apply false
}` in my root build.gradle and don't apply it, then ,in each module, i just need to add `plugins {
    id 'com.google.devtools.ksp' 
}` in  the module's build.gradle  convention scope. @ArtRoman 
--

**Comment by artroman** [comment]
This issue is just about readme.md as instruction for people who will use this library, this is only recommendations to make it usable in easy way, with less changes. Of course I'm not talking about applying this build settings to the project itself.

**Comment by mistletoe5215** [comment]
ok, i've update it ,appreciate your recommendations ~,QAQ.~ @ArtRoman

**Comment by artroman** [comment]
Thank you! 👍

I've found that `    id 'com.google.devtools.ksp' version '1.6.21-1.0.5'` in root build.gradle is new style of dependendies instead of setting classpath, so it should be project-dependent.
